library(glue)
library(cowplot)
library(magrittr)
library(plotly)
library(tidyverse)
library(widyr)
# Date & Time Manipulation.
library(hms)
library(lubridate) 
# Text Mining
library(tidytext)
library(tm)
library(wordcloud)
# Network Analysis
library(igraph)
# Network Visualization (D3.js)
library(networkD3)
#FILE_DIR <- dirname(rstudioapi::getSourceEditorContext()$path)
FILE_DIR <- getwd()
setwd(FILE_DIR)
PARENT_DIR <- file.path(FILE_DIR, "..")
arti <- paste0("articles/Original.txt")
text <- readLines(file.path(getwd(), arti))
text_df <- tibble(line = 1:length(text), text = text)